name: EatChicken
version: '${project.version}'
main: me.matt.eatchicken.EatChicken
api-version: '1.20'
authors: [Mattgyve1990]
description: Eat the chicken by pressing the RBM while sitting on the shift.
